//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShamanOjosDelCieloService.WSOjos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.lineasodc.com.ar/", ConfigurationName="WSOjos.OdcMedicoWebServiceSoap")]
    public interface OdcMedicoWebServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento cliente del espacio de nombres http://www.lineasodc.com.ar/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.lineasodc.com.ar/GetMovilesCercanos", ReplyAction="*")]
        ShamanOjosDelCieloService.WSOjos.GetMovilesCercanosResponse GetMovilesCercanos(ShamanOjosDelCieloService.WSOjos.GetMovilesCercanosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.lineasodc.com.ar/GetMovilesCercanos", ReplyAction="*")]
        System.Threading.Tasks.Task<ShamanOjosDelCieloService.WSOjos.GetMovilesCercanosResponse> GetMovilesCercanosAsync(ShamanOjosDelCieloService.WSOjos.GetMovilesCercanosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HashPingResult del espacio de nombres http://www.lineasodc.com.ar/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.lineasodc.com.ar/HashPing", ReplyAction="*")]
        ShamanOjosDelCieloService.WSOjos.HashPingResponse HashPing(ShamanOjosDelCieloService.WSOjos.HashPingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.lineasodc.com.ar/HashPing", ReplyAction="*")]
        System.Threading.Tasks.Task<ShamanOjosDelCieloService.WSOjos.HashPingResponse> HashPingAsync(ShamanOjosDelCieloService.WSOjos.HashPingRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento cliente del espacio de nombres http://www.lineasodc.com.ar/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.lineasodc.com.ar/GetPosicionMovil", ReplyAction="*")]
        ShamanOjosDelCieloService.WSOjos.GetPosicionMovilResponse GetPosicionMovil(ShamanOjosDelCieloService.WSOjos.GetPosicionMovilRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.lineasodc.com.ar/GetPosicionMovil", ReplyAction="*")]
        System.Threading.Tasks.Task<ShamanOjosDelCieloService.WSOjos.GetPosicionMovilResponse> GetPosicionMovilAsync(ShamanOjosDelCieloService.WSOjos.GetPosicionMovilRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento cliente del espacio de nombres http://www.lineasodc.com.ar/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.lineasodc.com.ar/GetPosicionMoviles", ReplyAction="*")]
        ShamanOjosDelCieloService.WSOjos.GetPosicionMovilesResponse GetPosicionMoviles(ShamanOjosDelCieloService.WSOjos.GetPosicionMovilesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.lineasodc.com.ar/GetPosicionMoviles", ReplyAction="*")]
        System.Threading.Tasks.Task<ShamanOjosDelCieloService.WSOjos.GetPosicionMovilesResponse> GetPosicionMovilesAsync(ShamanOjosDelCieloService.WSOjos.GetPosicionMovilesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento cliente del espacio de nombres http://www.lineasodc.com.ar/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.lineasodc.com.ar/SetCambioEstado", ReplyAction="*")]
        ShamanOjosDelCieloService.WSOjos.SetCambioEstadoResponse SetCambioEstado(ShamanOjosDelCieloService.WSOjos.SetCambioEstadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.lineasodc.com.ar/SetCambioEstado", ReplyAction="*")]
        System.Threading.Tasks.Task<ShamanOjosDelCieloService.WSOjos.SetCambioEstadoResponse> SetCambioEstadoAsync(ShamanOjosDelCieloService.WSOjos.SetCambioEstadoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento cliente del espacio de nombres http://www.lineasodc.com.ar/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.lineasodc.com.ar/SetCambioZona", ReplyAction="*")]
        ShamanOjosDelCieloService.WSOjos.SetCambioZonaResponse SetCambioZona(ShamanOjosDelCieloService.WSOjos.SetCambioZonaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.lineasodc.com.ar/SetCambioZona", ReplyAction="*")]
        System.Threading.Tasks.Task<ShamanOjosDelCieloService.WSOjos.SetCambioZonaResponse> SetCambioZonaAsync(ShamanOjosDelCieloService.WSOjos.SetCambioZonaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMovilesCercanosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMovilesCercanos", Namespace="http://www.lineasodc.com.ar/", Order=0)]
        public ShamanOjosDelCieloService.WSOjos.GetMovilesCercanosRequestBody Body;
        
        public GetMovilesCercanosRequest() {
        }
        
        public GetMovilesCercanosRequest(ShamanOjosDelCieloService.WSOjos.GetMovilesCercanosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.lineasodc.com.ar/")]
    public partial class GetMovilesCercanosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string firma;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string time;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public double latitud;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public double longitud;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int maxCantidadATraer;
        
        public GetMovilesCercanosRequestBody() {
        }
        
        public GetMovilesCercanosRequestBody(string cliente, string firma, string time, double latitud, double longitud, int maxCantidadATraer) {
            this.cliente = cliente;
            this.firma = firma;
            this.time = time;
            this.latitud = latitud;
            this.longitud = longitud;
            this.maxCantidadATraer = maxCantidadATraer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMovilesCercanosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMovilesCercanosResponse", Namespace="http://www.lineasodc.com.ar/", Order=0)]
        public ShamanOjosDelCieloService.WSOjos.GetMovilesCercanosResponseBody Body;
        
        public GetMovilesCercanosResponse() {
        }
        
        public GetMovilesCercanosResponse(ShamanOjosDelCieloService.WSOjos.GetMovilesCercanosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.lineasodc.com.ar/")]
    public partial class GetMovilesCercanosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetMovilesCercanosResult;
        
        public GetMovilesCercanosResponseBody() {
        }
        
        public GetMovilesCercanosResponseBody(System.Xml.Linq.XElement GetMovilesCercanosResult) {
            this.GetMovilesCercanosResult = GetMovilesCercanosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HashPingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HashPing", Namespace="http://www.lineasodc.com.ar/", Order=0)]
        public ShamanOjosDelCieloService.WSOjos.HashPingRequestBody Body;
        
        public HashPingRequest() {
        }
        
        public HashPingRequest(ShamanOjosDelCieloService.WSOjos.HashPingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HashPingRequestBody {
        
        public HashPingRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HashPingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HashPingResponse", Namespace="http://www.lineasodc.com.ar/", Order=0)]
        public ShamanOjosDelCieloService.WSOjos.HashPingResponseBody Body;
        
        public HashPingResponse() {
        }
        
        public HashPingResponse(ShamanOjosDelCieloService.WSOjos.HashPingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.lineasodc.com.ar/")]
    public partial class HashPingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement HashPingResult;
        
        public HashPingResponseBody() {
        }
        
        public HashPingResponseBody(System.Xml.Linq.XElement HashPingResult) {
            this.HashPingResult = HashPingResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPosicionMovilRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPosicionMovil", Namespace="http://www.lineasodc.com.ar/", Order=0)]
        public ShamanOjosDelCieloService.WSOjos.GetPosicionMovilRequestBody Body;
        
        public GetPosicionMovilRequest() {
        }
        
        public GetPosicionMovilRequest(ShamanOjosDelCieloService.WSOjos.GetPosicionMovilRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.lineasodc.com.ar/")]
    public partial class GetPosicionMovilRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string firma;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string time;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string movil;
        
        public GetPosicionMovilRequestBody() {
        }
        
        public GetPosicionMovilRequestBody(string cliente, string firma, string time, string movil) {
            this.cliente = cliente;
            this.firma = firma;
            this.time = time;
            this.movil = movil;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPosicionMovilResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPosicionMovilResponse", Namespace="http://www.lineasodc.com.ar/", Order=0)]
        public ShamanOjosDelCieloService.WSOjos.GetPosicionMovilResponseBody Body;
        
        public GetPosicionMovilResponse() {
        }
        
        public GetPosicionMovilResponse(ShamanOjosDelCieloService.WSOjos.GetPosicionMovilResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.lineasodc.com.ar/")]
    public partial class GetPosicionMovilResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetPosicionMovilResult;
        
        public GetPosicionMovilResponseBody() {
        }
        
        public GetPosicionMovilResponseBody(System.Xml.Linq.XElement GetPosicionMovilResult) {
            this.GetPosicionMovilResult = GetPosicionMovilResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPosicionMovilesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPosicionMoviles", Namespace="http://www.lineasodc.com.ar/", Order=0)]
        public ShamanOjosDelCieloService.WSOjos.GetPosicionMovilesRequestBody Body;
        
        public GetPosicionMovilesRequest() {
        }
        
        public GetPosicionMovilesRequest(ShamanOjosDelCieloService.WSOjos.GetPosicionMovilesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.lineasodc.com.ar/")]
    public partial class GetPosicionMovilesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string firma;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string time;
        
        public GetPosicionMovilesRequestBody() {
        }
        
        public GetPosicionMovilesRequestBody(string cliente, string firma, string time) {
            this.cliente = cliente;
            this.firma = firma;
            this.time = time;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPosicionMovilesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPosicionMovilesResponse", Namespace="http://www.lineasodc.com.ar/", Order=0)]
        public ShamanOjosDelCieloService.WSOjos.GetPosicionMovilesResponseBody Body;
        
        public GetPosicionMovilesResponse() {
        }
        
        public GetPosicionMovilesResponse(ShamanOjosDelCieloService.WSOjos.GetPosicionMovilesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.lineasodc.com.ar/")]
    public partial class GetPosicionMovilesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetPosicionMovilesResult;
        
        public GetPosicionMovilesResponseBody() {
        }
        
        public GetPosicionMovilesResponseBody(System.Xml.Linq.XElement GetPosicionMovilesResult) {
            this.GetPosicionMovilesResult = GetPosicionMovilesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetCambioEstadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetCambioEstado", Namespace="http://www.lineasodc.com.ar/", Order=0)]
        public ShamanOjosDelCieloService.WSOjos.SetCambioEstadoRequestBody Body;
        
        public SetCambioEstadoRequest() {
        }
        
        public SetCambioEstadoRequest(ShamanOjosDelCieloService.WSOjos.SetCambioEstadoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.lineasodc.com.ar/")]
    public partial class SetCambioEstadoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string firma;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string time;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string movil;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string nivel1;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int nivel2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public System.Xml.Linq.XElement empleados;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public System.Xml.Linq.XElement descripciones;
        
        public SetCambioEstadoRequestBody() {
        }
        
        public SetCambioEstadoRequestBody(string cliente, string firma, string time, string movil, string nivel1, int nivel2, System.Xml.Linq.XElement empleados, System.Xml.Linq.XElement descripciones) {
            this.cliente = cliente;
            this.firma = firma;
            this.time = time;
            this.movil = movil;
            this.nivel1 = nivel1;
            this.nivel2 = nivel2;
            this.empleados = empleados;
            this.descripciones = descripciones;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetCambioEstadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetCambioEstadoResponse", Namespace="http://www.lineasodc.com.ar/", Order=0)]
        public ShamanOjosDelCieloService.WSOjos.SetCambioEstadoResponseBody Body;
        
        public SetCambioEstadoResponse() {
        }
        
        public SetCambioEstadoResponse(ShamanOjosDelCieloService.WSOjos.SetCambioEstadoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.lineasodc.com.ar/")]
    public partial class SetCambioEstadoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement SetCambioEstadoResult;
        
        public SetCambioEstadoResponseBody() {
        }
        
        public SetCambioEstadoResponseBody(System.Xml.Linq.XElement SetCambioEstadoResult) {
            this.SetCambioEstadoResult = SetCambioEstadoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetCambioZonaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetCambioZona", Namespace="http://www.lineasodc.com.ar/", Order=0)]
        public ShamanOjosDelCieloService.WSOjos.SetCambioZonaRequestBody Body;
        
        public SetCambioZonaRequest() {
        }
        
        public SetCambioZonaRequest(ShamanOjosDelCieloService.WSOjos.SetCambioZonaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.lineasodc.com.ar/")]
    public partial class SetCambioZonaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string firma;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string time;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string movil;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public System.Xml.Linq.XElement zonas;
        
        public SetCambioZonaRequestBody() {
        }
        
        public SetCambioZonaRequestBody(string cliente, string firma, string time, string movil, System.Xml.Linq.XElement zonas) {
            this.cliente = cliente;
            this.firma = firma;
            this.time = time;
            this.movil = movil;
            this.zonas = zonas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetCambioZonaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetCambioZonaResponse", Namespace="http://www.lineasodc.com.ar/", Order=0)]
        public ShamanOjosDelCieloService.WSOjos.SetCambioZonaResponseBody Body;
        
        public SetCambioZonaResponse() {
        }
        
        public SetCambioZonaResponse(ShamanOjosDelCieloService.WSOjos.SetCambioZonaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.lineasodc.com.ar/")]
    public partial class SetCambioZonaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement SetCambioZonaResult;
        
        public SetCambioZonaResponseBody() {
        }
        
        public SetCambioZonaResponseBody(System.Xml.Linq.XElement SetCambioZonaResult) {
            this.SetCambioZonaResult = SetCambioZonaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OdcMedicoWebServiceSoapChannel : ShamanOjosDelCieloService.WSOjos.OdcMedicoWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OdcMedicoWebServiceSoapClient : System.ServiceModel.ClientBase<ShamanOjosDelCieloService.WSOjos.OdcMedicoWebServiceSoap>, ShamanOjosDelCieloService.WSOjos.OdcMedicoWebServiceSoap {
        
        public OdcMedicoWebServiceSoapClient() {
        }
        
        public OdcMedicoWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OdcMedicoWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OdcMedicoWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OdcMedicoWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ShamanOjosDelCieloService.WSOjos.GetMovilesCercanosResponse ShamanOjosDelCieloService.WSOjos.OdcMedicoWebServiceSoap.GetMovilesCercanos(ShamanOjosDelCieloService.WSOjos.GetMovilesCercanosRequest request) {
            return base.Channel.GetMovilesCercanos(request);
        }
        
        public System.Xml.Linq.XElement GetMovilesCercanos(string cliente, string firma, string time, double latitud, double longitud, int maxCantidadATraer) {
            ShamanOjosDelCieloService.WSOjos.GetMovilesCercanosRequest inValue = new ShamanOjosDelCieloService.WSOjos.GetMovilesCercanosRequest();
            inValue.Body = new ShamanOjosDelCieloService.WSOjos.GetMovilesCercanosRequestBody();
            inValue.Body.cliente = cliente;
            inValue.Body.firma = firma;
            inValue.Body.time = time;
            inValue.Body.latitud = latitud;
            inValue.Body.longitud = longitud;
            inValue.Body.maxCantidadATraer = maxCantidadATraer;
            ShamanOjosDelCieloService.WSOjos.GetMovilesCercanosResponse retVal = ((ShamanOjosDelCieloService.WSOjos.OdcMedicoWebServiceSoap)(this)).GetMovilesCercanos(inValue);
            return retVal.Body.GetMovilesCercanosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ShamanOjosDelCieloService.WSOjos.GetMovilesCercanosResponse> ShamanOjosDelCieloService.WSOjos.OdcMedicoWebServiceSoap.GetMovilesCercanosAsync(ShamanOjosDelCieloService.WSOjos.GetMovilesCercanosRequest request) {
            return base.Channel.GetMovilesCercanosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ShamanOjosDelCieloService.WSOjos.GetMovilesCercanosResponse> GetMovilesCercanosAsync(string cliente, string firma, string time, double latitud, double longitud, int maxCantidadATraer) {
            ShamanOjosDelCieloService.WSOjos.GetMovilesCercanosRequest inValue = new ShamanOjosDelCieloService.WSOjos.GetMovilesCercanosRequest();
            inValue.Body = new ShamanOjosDelCieloService.WSOjos.GetMovilesCercanosRequestBody();
            inValue.Body.cliente = cliente;
            inValue.Body.firma = firma;
            inValue.Body.time = time;
            inValue.Body.latitud = latitud;
            inValue.Body.longitud = longitud;
            inValue.Body.maxCantidadATraer = maxCantidadATraer;
            return ((ShamanOjosDelCieloService.WSOjos.OdcMedicoWebServiceSoap)(this)).GetMovilesCercanosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ShamanOjosDelCieloService.WSOjos.HashPingResponse ShamanOjosDelCieloService.WSOjos.OdcMedicoWebServiceSoap.HashPing(ShamanOjosDelCieloService.WSOjos.HashPingRequest request) {
            return base.Channel.HashPing(request);
        }
        
        public System.Xml.Linq.XElement HashPing() {
            ShamanOjosDelCieloService.WSOjos.HashPingRequest inValue = new ShamanOjosDelCieloService.WSOjos.HashPingRequest();
            inValue.Body = new ShamanOjosDelCieloService.WSOjos.HashPingRequestBody();
            ShamanOjosDelCieloService.WSOjos.HashPingResponse retVal = ((ShamanOjosDelCieloService.WSOjos.OdcMedicoWebServiceSoap)(this)).HashPing(inValue);
            return retVal.Body.HashPingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ShamanOjosDelCieloService.WSOjos.HashPingResponse> ShamanOjosDelCieloService.WSOjos.OdcMedicoWebServiceSoap.HashPingAsync(ShamanOjosDelCieloService.WSOjos.HashPingRequest request) {
            return base.Channel.HashPingAsync(request);
        }
        
        public System.Threading.Tasks.Task<ShamanOjosDelCieloService.WSOjos.HashPingResponse> HashPingAsync() {
            ShamanOjosDelCieloService.WSOjos.HashPingRequest inValue = new ShamanOjosDelCieloService.WSOjos.HashPingRequest();
            inValue.Body = new ShamanOjosDelCieloService.WSOjos.HashPingRequestBody();
            return ((ShamanOjosDelCieloService.WSOjos.OdcMedicoWebServiceSoap)(this)).HashPingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ShamanOjosDelCieloService.WSOjos.GetPosicionMovilResponse ShamanOjosDelCieloService.WSOjos.OdcMedicoWebServiceSoap.GetPosicionMovil(ShamanOjosDelCieloService.WSOjos.GetPosicionMovilRequest request) {
            return base.Channel.GetPosicionMovil(request);
        }
        
        public System.Xml.Linq.XElement GetPosicionMovil(string cliente, string firma, string time, string movil) {
            ShamanOjosDelCieloService.WSOjos.GetPosicionMovilRequest inValue = new ShamanOjosDelCieloService.WSOjos.GetPosicionMovilRequest();
            inValue.Body = new ShamanOjosDelCieloService.WSOjos.GetPosicionMovilRequestBody();
            inValue.Body.cliente = cliente;
            inValue.Body.firma = firma;
            inValue.Body.time = time;
            inValue.Body.movil = movil;
            ShamanOjosDelCieloService.WSOjos.GetPosicionMovilResponse retVal = ((ShamanOjosDelCieloService.WSOjos.OdcMedicoWebServiceSoap)(this)).GetPosicionMovil(inValue);
            return retVal.Body.GetPosicionMovilResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ShamanOjosDelCieloService.WSOjos.GetPosicionMovilResponse> ShamanOjosDelCieloService.WSOjos.OdcMedicoWebServiceSoap.GetPosicionMovilAsync(ShamanOjosDelCieloService.WSOjos.GetPosicionMovilRequest request) {
            return base.Channel.GetPosicionMovilAsync(request);
        }
        
        public System.Threading.Tasks.Task<ShamanOjosDelCieloService.WSOjos.GetPosicionMovilResponse> GetPosicionMovilAsync(string cliente, string firma, string time, string movil) {
            ShamanOjosDelCieloService.WSOjos.GetPosicionMovilRequest inValue = new ShamanOjosDelCieloService.WSOjos.GetPosicionMovilRequest();
            inValue.Body = new ShamanOjosDelCieloService.WSOjos.GetPosicionMovilRequestBody();
            inValue.Body.cliente = cliente;
            inValue.Body.firma = firma;
            inValue.Body.time = time;
            inValue.Body.movil = movil;
            return ((ShamanOjosDelCieloService.WSOjos.OdcMedicoWebServiceSoap)(this)).GetPosicionMovilAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ShamanOjosDelCieloService.WSOjos.GetPosicionMovilesResponse ShamanOjosDelCieloService.WSOjos.OdcMedicoWebServiceSoap.GetPosicionMoviles(ShamanOjosDelCieloService.WSOjos.GetPosicionMovilesRequest request) {
            return base.Channel.GetPosicionMoviles(request);
        }
        
        public System.Xml.Linq.XElement GetPosicionMoviles(string cliente, string firma, string time) {
            ShamanOjosDelCieloService.WSOjos.GetPosicionMovilesRequest inValue = new ShamanOjosDelCieloService.WSOjos.GetPosicionMovilesRequest();
            inValue.Body = new ShamanOjosDelCieloService.WSOjos.GetPosicionMovilesRequestBody();
            inValue.Body.cliente = cliente;
            inValue.Body.firma = firma;
            inValue.Body.time = time;
            ShamanOjosDelCieloService.WSOjos.GetPosicionMovilesResponse retVal = ((ShamanOjosDelCieloService.WSOjos.OdcMedicoWebServiceSoap)(this)).GetPosicionMoviles(inValue);
            return retVal.Body.GetPosicionMovilesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ShamanOjosDelCieloService.WSOjos.GetPosicionMovilesResponse> ShamanOjosDelCieloService.WSOjos.OdcMedicoWebServiceSoap.GetPosicionMovilesAsync(ShamanOjosDelCieloService.WSOjos.GetPosicionMovilesRequest request) {
            return base.Channel.GetPosicionMovilesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ShamanOjosDelCieloService.WSOjos.GetPosicionMovilesResponse> GetPosicionMovilesAsync(string cliente, string firma, string time) {
            ShamanOjosDelCieloService.WSOjos.GetPosicionMovilesRequest inValue = new ShamanOjosDelCieloService.WSOjos.GetPosicionMovilesRequest();
            inValue.Body = new ShamanOjosDelCieloService.WSOjos.GetPosicionMovilesRequestBody();
            inValue.Body.cliente = cliente;
            inValue.Body.firma = firma;
            inValue.Body.time = time;
            return ((ShamanOjosDelCieloService.WSOjos.OdcMedicoWebServiceSoap)(this)).GetPosicionMovilesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ShamanOjosDelCieloService.WSOjos.SetCambioEstadoResponse ShamanOjosDelCieloService.WSOjos.OdcMedicoWebServiceSoap.SetCambioEstado(ShamanOjosDelCieloService.WSOjos.SetCambioEstadoRequest request) {
            return base.Channel.SetCambioEstado(request);
        }
        
        public System.Xml.Linq.XElement SetCambioEstado(string cliente, string firma, string time, string movil, string nivel1, int nivel2, System.Xml.Linq.XElement empleados, System.Xml.Linq.XElement descripciones) {
            ShamanOjosDelCieloService.WSOjos.SetCambioEstadoRequest inValue = new ShamanOjosDelCieloService.WSOjos.SetCambioEstadoRequest();
            inValue.Body = new ShamanOjosDelCieloService.WSOjos.SetCambioEstadoRequestBody();
            inValue.Body.cliente = cliente;
            inValue.Body.firma = firma;
            inValue.Body.time = time;
            inValue.Body.movil = movil;
            inValue.Body.nivel1 = nivel1;
            inValue.Body.nivel2 = nivel2;
            inValue.Body.empleados = empleados;
            inValue.Body.descripciones = descripciones;
            ShamanOjosDelCieloService.WSOjos.SetCambioEstadoResponse retVal = ((ShamanOjosDelCieloService.WSOjos.OdcMedicoWebServiceSoap)(this)).SetCambioEstado(inValue);
            return retVal.Body.SetCambioEstadoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ShamanOjosDelCieloService.WSOjos.SetCambioEstadoResponse> ShamanOjosDelCieloService.WSOjos.OdcMedicoWebServiceSoap.SetCambioEstadoAsync(ShamanOjosDelCieloService.WSOjos.SetCambioEstadoRequest request) {
            return base.Channel.SetCambioEstadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ShamanOjosDelCieloService.WSOjos.SetCambioEstadoResponse> SetCambioEstadoAsync(string cliente, string firma, string time, string movil, string nivel1, int nivel2, System.Xml.Linq.XElement empleados, System.Xml.Linq.XElement descripciones) {
            ShamanOjosDelCieloService.WSOjos.SetCambioEstadoRequest inValue = new ShamanOjosDelCieloService.WSOjos.SetCambioEstadoRequest();
            inValue.Body = new ShamanOjosDelCieloService.WSOjos.SetCambioEstadoRequestBody();
            inValue.Body.cliente = cliente;
            inValue.Body.firma = firma;
            inValue.Body.time = time;
            inValue.Body.movil = movil;
            inValue.Body.nivel1 = nivel1;
            inValue.Body.nivel2 = nivel2;
            inValue.Body.empleados = empleados;
            inValue.Body.descripciones = descripciones;
            return ((ShamanOjosDelCieloService.WSOjos.OdcMedicoWebServiceSoap)(this)).SetCambioEstadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ShamanOjosDelCieloService.WSOjos.SetCambioZonaResponse ShamanOjosDelCieloService.WSOjos.OdcMedicoWebServiceSoap.SetCambioZona(ShamanOjosDelCieloService.WSOjos.SetCambioZonaRequest request) {
            return base.Channel.SetCambioZona(request);
        }
        
        public System.Xml.Linq.XElement SetCambioZona(string cliente, string firma, string time, string movil, System.Xml.Linq.XElement zonas) {
            ShamanOjosDelCieloService.WSOjos.SetCambioZonaRequest inValue = new ShamanOjosDelCieloService.WSOjos.SetCambioZonaRequest();
            inValue.Body = new ShamanOjosDelCieloService.WSOjos.SetCambioZonaRequestBody();
            inValue.Body.cliente = cliente;
            inValue.Body.firma = firma;
            inValue.Body.time = time;
            inValue.Body.movil = movil;
            inValue.Body.zonas = zonas;
            ShamanOjosDelCieloService.WSOjos.SetCambioZonaResponse retVal = ((ShamanOjosDelCieloService.WSOjos.OdcMedicoWebServiceSoap)(this)).SetCambioZona(inValue);
            return retVal.Body.SetCambioZonaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ShamanOjosDelCieloService.WSOjos.SetCambioZonaResponse> ShamanOjosDelCieloService.WSOjos.OdcMedicoWebServiceSoap.SetCambioZonaAsync(ShamanOjosDelCieloService.WSOjos.SetCambioZonaRequest request) {
            return base.Channel.SetCambioZonaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ShamanOjosDelCieloService.WSOjos.SetCambioZonaResponse> SetCambioZonaAsync(string cliente, string firma, string time, string movil, System.Xml.Linq.XElement zonas) {
            ShamanOjosDelCieloService.WSOjos.SetCambioZonaRequest inValue = new ShamanOjosDelCieloService.WSOjos.SetCambioZonaRequest();
            inValue.Body = new ShamanOjosDelCieloService.WSOjos.SetCambioZonaRequestBody();
            inValue.Body.cliente = cliente;
            inValue.Body.firma = firma;
            inValue.Body.time = time;
            inValue.Body.movil = movil;
            inValue.Body.zonas = zonas;
            return ((ShamanOjosDelCieloService.WSOjos.OdcMedicoWebServiceSoap)(this)).SetCambioZonaAsync(inValue);
        }
    }
}
